# Generated by Django 2.2.5 on 2020-06-02 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('caminhoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mtr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('alias', models.CharField(max_length=155, verbose_name='alias')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da saida')),
                ('chegada', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da chegada')),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caminhoes.Caminhoes')),
                ('cliente', models.ManyToManyField(to='clientes.Cliente')),
            ],
        ),
    ]
