# Generated by Django 2.2.5 on 2020-07-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencia', '0003_remove_sequencia_mtr'),
        ('mtr', '0003_remove_mtr_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtr',
            name='sequencia',
            field=models.ManyToManyField(to='sequencia.Sequencia'),
        ),
    ]
