# Generated by Django 2.2.5 on 2020-06-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200602_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Motorista'), ('3', 'Cliente')], max_length=1, verbose_name='Tipo'),
        ),
    ]
