# Generated by Django 2.2.5 on 2020-07-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtrv2', '0002_mtrv2_motorista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtrv2',
            name='motorista',
        ),
    ]
