# Generated by Django 2.2.5 on 2020-06-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_multidev', models.IntegerField(verbose_name='Id Multidev')),
                ('razao_social', models.CharField(max_length=115, verbose_name='Razão Social')),
                ('fantasia', models.CharField(max_length=115, verbose_name='Nome Fantasia')),
                ('logradouro', models.CharField(blank=True, max_length=115, null=True, verbose_name='Logradouro')),
                ('bairro', models.CharField(blank=True, max_length=115, null=True, verbose_name='Bairro')),
                ('municipio', models.CharField(blank=True, max_length=115, null=True, verbose_name='Municipio')),
                ('estado', models.CharField(blank=True, max_length=115, null=True, verbose_name='Estado')),
                ('latitude', models.CharField(max_length=100, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=100, verbose_name='Longitude')),
            ],
        ),
    ]
