# Generated by Django 2.2.5 on 2020-06-12 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='gestao',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
