# Generated by Django 2.2.5 on 2020-06-12 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0002_cliente_gestao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='gestao',
        ),
        migrations.AddField(
            model_name='cliente',
            name='gestao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
