# Generated by Django 2.2.5 on 2020-08-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtritem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtritem',
            name='latitude',
            field=models.CharField(default=1, max_length=150, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtritem',
            name='longitude',
            field=models.CharField(default=1, max_length=150, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
