# Generated by Django 2.2.5 on 2020-07-09 10:08

from django.db import migrations, models
import django.db.models.deletion
#

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_auto_20200612_1452'),
        ('mtr', '0002_auto_20200709_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=155, verbose_name='Rua')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('bairro', models.CharField(max_length=155, verbose_name='Bairro')),
                ('municipio', models.CharField(max_length=155, verbose_name='Municipio')),
                ('estado', models.CharField(max_length=155, verbose_name='Estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('mtr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtr.Mtr')),
            ],
        ),
    ]
