# Generated by Django 2.2.5 on 2020-06-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motoristas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_multidev', models.IntegerField(verbose_name='Id Multidev')),
                ('nome', models.CharField(max_length=115, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('mopp', models.CharField(blank=True, max_length=20, null=True, verbose_name='MOPP')),
                ('mopp_validade', models.DateField(blank=True, null=True, verbose_name='Validade MOPP')),
                ('cnh', models.CharField(max_length=20, verbose_name='CNH')),
                ('cnh_categoria', models.CharField(max_length=2, verbose_name='Categoria Cnh')),
                ('cnh_validade', models.DateField(verbose_name='Validade CNH')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitude')),
            ],
        ),
    ]
