# Generated by Django 2.2.5 on 2020-06-03 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0002_motoristas_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motoristas',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='motoristas',
            name='longitude',
        ),
    ]
